name: jr-web-app # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Node.js REST App packaged as snap # 79 char long summary
description: |
  Snap that publish a Node.js App server for SPA that listen for GET request

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  snap-web-app:
    plugin: npm
    npm-include-node: true
    npm-node-version: 18.16.1
    source: .
apps:
  snap-web-app:
    command: bin/start
    daemon: simple
    plugs:
      - network
      - network-bind